/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as ShoppingCartIndexRouteImport } from './routes/shopping-cart/index'
import { Route as FrShoppingCartIndexRouteImport } from './routes/fr/shopping-cart/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingCartIndexRoute = ShoppingCartIndexRouteImport.update({
  id: '/shopping-cart/',
  path: '/shopping-cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrShoppingCartIndexRoute = FrShoppingCartIndexRouteImport.update({
  id: '/fr/shopping-cart/',
  path: '/fr/shopping-cart/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/shopping-cart/': typeof ShoppingCartIndexRoute
  '/fr/shopping-cart/': typeof FrShoppingCartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fr': typeof FrIndexRoute
  '/shopping-cart': typeof ShoppingCartIndexRoute
  '/fr/shopping-cart': typeof FrShoppingCartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fr/': typeof FrIndexRoute
  '/shopping-cart/': typeof ShoppingCartIndexRoute
  '/fr/shopping-cart/': typeof FrShoppingCartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fr/' | '/shopping-cart/' | '/fr/shopping-cart/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fr' | '/shopping-cart' | '/fr/shopping-cart'
  id: '__root__' | '/' | '/fr/' | '/shopping-cart/' | '/fr/shopping-cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrIndexRoute: typeof FrIndexRoute
  ShoppingCartIndexRoute: typeof ShoppingCartIndexRoute
  FrShoppingCartIndexRoute: typeof FrShoppingCartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-cart/': {
      id: '/shopping-cart/'
      path: '/shopping-cart'
      fullPath: '/shopping-cart/'
      preLoaderRoute: typeof ShoppingCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/shopping-cart/': {
      id: '/fr/shopping-cart/'
      path: '/fr/shopping-cart'
      fullPath: '/fr/shopping-cart/'
      preLoaderRoute: typeof FrShoppingCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrIndexRoute: FrIndexRoute,
  ShoppingCartIndexRoute: ShoppingCartIndexRoute,
  FrShoppingCartIndexRoute: FrShoppingCartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
